config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index,:show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :doses, dependent: :destroy 
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  
  def index
    @cocktails = Cocktail.all
  end
  
 def show
   @cocktail = Cocktail.find(params[:id])
 end
 

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      flash[:success] = "Creado Con exito"
      redirect_to @cocktail
    else
      flash[:error] = "Intenta nuevamente"
      render 'new'
    end
  end
  
  def destroy
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.destroy
      flash[:success] = 'Eliminado con exito'
      redirect_to cocktails_url
    else
      flash[:error] = 'No se pudo eliminar'
      redirect_to cocktails_url
    end
  end
  

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
  
  
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.find(params[:dose][:ingredient_id])
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    if @dose.destroy
      flash[:success] = 'Eliminado.'
      redirect_to cocktail_path(params[:cocktail_id])
    else
      flash[:error] = 'No es posible'
      redirect_to doses_url
    end
  end
  

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    @review.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container">

 <%# BUSCADOR %>
  <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group mt-4">
    <input class="form-control string required" type="text" name="" id="" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Buscar pack
    </button>
  </div>
  </form>

  <%#VOLVER AL INICIOO  %>
  <%= link_to "Inicio",  cocktails_path, class: "btn btn-outline-dark mt-2 mb-2" %>


  <%# AGREGAR Bebida %>
  <%= link_to "Agregar pack",  new_cocktail_path, class: "btn btn-outline-dark " %>

  <%# IMAGEN PRINCIPAL %>
  <%= image_tag "https://i.pinimg.com/originals/fe/50/ea/fe50ea2c098f4560ba6c2a3e897c9d30.png", class: "img-fluid mx-auto d-block" %>

  <%# TODOS LOS TRAGOS %>

  <h6>Contamos con <%= @cocktails.count %> promos </h6>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-md-3 my-3">
        <div class="card-img-top">
        <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key, height: 300, width: 300, crop: :fill, class: "img-fluid" %>
        <% else %>
          <%= cl_image_tag "nodisponible", height: 300, width: 300, crop: :fill, class: "img-fluid" %>
        <% end %>
          <h4><%= cocktail["name"] %></h4>
        </div>

        <div class="card-footer">
          <%# MAS INFO %>
          <%= link_to "Ver mas", cocktail_path(cocktail["id"]), class: "btn btn-outline-dark" %>
          <%# DELETE %>
          <%= link_to "Borrar", cocktail_path(cocktail["id"]), method: :delete , class: "btn btn-outline-danger" %>
        </div>
      </div>
    <% end %>
  </div>

  <%# FOOTER %>
  <div class="footer">
  <div class="footer-links">
    <a href="https://github.com/benjakunkel"><i class="fab fa-github" id="git"></i></a>
    <a href="https://www.instagram.com/benjakunkel/"><i class="fab fa-instagram" id="insta"></i></a>
    <a href="https://www.linkedin.com/in/benjamin-kunkel-3744a51a7/"><i class="fab fa-linkedin" id="link"></i></a>
  </div>

</div>

app/views/cocktails/new.html.erb
<div class="container">

<%# VOLVER AL INICOO %>
  <%= link_to "Inicio",  cocktails_path, class: "btn btn-outline-dark mt-3 mb-3 " %>

  <%# FORMULARIO %>
  <div class="form-group text-center">
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name,  :label => "Ingresa tu pack:",placeholder:"Nombre del producto", class:"saraza" %>
      <%= f.input :photo, as: :file, class:"boton subir"  %>
      <%= f.submit "Agregar producto", class:"btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <%#VOLVER AL INICIOO  %>
  <%= link_to "Inicio",  cocktails_path, class: "btn btn-outline-dark mt-3 mb-3" %>

  <%# agregar doseses %>
  <%= link_to "Agregar producto al pack",  new_cocktail_dose_path(@cocktail), class:"btn btn-outline-dark mt-3 mb-3" %>
<%# ADD REVIEW %>
  <%= link_to 'Agregar review', new_cocktail_review_path(@cocktail), class: "btn btn-outline-dark m-2" %>
  <%# INTENTO DE CARD %>
    <div class="card mb-3 mx-auto" style="max-width: 1000px;">
      <div class="row no-gutters">
        <div class="col-md-6">
          <% if @cocktail.photo.attached? %>
          <%= cl_image_tag @cocktail.photo.key, height: 300, width: 300, crop: :fill, class: "img-fluid" %>
        <% else %>
          <%= cl_image_tag "nodisponible", height: 300, width: 300, crop: :fill, class: "img-fluid" %>
        <% end %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h5 class="card-title">Contenido del pack</h5>
            <ul class="list-group">
              <% @cocktail.doses.each do |dose| %>
                <li class="list-group-item mb-3">
                <%= dose.description  %>
                <strong> <%= dose.ingredient.name  %> </strong>
                <%= link_to "Delete", cocktail_dose_path(@cocktail, dose), method: :delete, class:"btn btn-danger btn-sm ml-4" %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
</div>
<div class="reviews">
  <h2 id="reviews">Reviews</h2>
  <ul class="nada">
  <% @cocktail.reviews.each do |review| %>
    <li class="list-group-item review-item"><%="⭐"*review.rating %>  <%= review.content %></li>
  <% end %>
</ul>
  </div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">
  Agregar Review
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal"> Cancelar </button>
        <button type="button" class="btn btn-dark"> Agregar </button>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">

<%# Agregar Cocktails %>
<%= simple_form_for [ @cocktail, @dose] do |t| %>
  <%= t.input :description %>
  <%= t.association :ingredient %>
  <%= t.submit class: "btn btn-dark" %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
<%= simple_form_for [ @cocktail, @review] do |t| %>
  <%= t.input :content %>
  <%= t.input :rating %>
  <%= t.submit class: "btn btn-dark" %>
<% end %>
</div>